apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tp-dp-hawk-console.consts.appName" . }}-certs
  labels:
    {{- include "tp-dp-hawk-console.shared.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "tp-dp-hawk-console.gencerts" . ) | indent 2 }}
