{{ if .Values.jaeger.ingress.enabled -}}
{{- $gateway := default "loib-it0611014-dev-ingressgateway" (tpl .Values.jaeger.ingress.className .) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jaeger-virtualservice
  labels:
    app.kubernetes.io/component: load-balancer
    {{- include "o11y-service.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-namespace: {{ .Values.global.cp.resources.serviceaccount.namespace }}
    meta.helm.sh/release-name: {{ include "o11y-service.fullname" . }}
    {{- with .Values.jaeger.ingress.annotations }}
      {{- tpl (. | toYaml) $ | nindent 4 }}
    {{- end }}
spec:
  hosts:
  {{- range .Values.jaeger.ingress.hosts }}
    {{- if .host }}
    - {{ .host | quote }}
    {{- else }}
    - "dp-{{ $.Values.global.cp.dataplaneId }}.platform.local"
    {{- end }}
  {{- end }}
  gateways:
    - {{ $gateway | quote }}
    - "mesh"
  http:
    {{- if $.Values.jaeger.ingress.hostsOverride -}}
    {{- range .Values.jaeger.ingress.hosts }}
    {{- range .paths }}
    - match:
        - uri:
            prefix: {{ .path }}
      route:
        - destination:
            host: {{ $.Values.jaeger.service.name }}.{{ $.Release.Namespace }}.svc.cluster.local
            port:
              number: {{ $.Values.jaeger.service.port }}
    {{- end }}
    {{- end }}
    {{- else}}
    - match:
        - uri:
            prefix: /tibco/agent/o11y/{{ $.Values.global.cp.instanceId }}/jaeger-query/
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ $.Values.jaeger.service.name }}.{{ $.Release.Namespace }}.svc.cluster.local
            port:
              number: {{ $.Values.jaeger.service.port }}
    {{- end }}
{{- end -}}
